project:
  type: book

book:
  title: Bestiario de Teoría de Números
  author: Enrique Pérez Herrero
  date: "15/10/2023"
  chapters:
    - index.qmd
    - book/00-Intro/intro.qmd
    - book/05-Ecuaciones/index.qmd
    - book/summary.qmd
    - book/references.qmd

bibliography: book/bib/references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

crossref:
  tbl-title: Tabla
  fig-title: Figura

